// <auto-generated />
using System;
using BAR.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BAR.Migrations
{
    [DbContext(typeof(BarDbContext))]
    [Migration("20260426104214_ChangeBalanceToLong")]
    partial class ChangeBalanceToLong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BAR.Database.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("BAR.Database.Entities.AccountPromo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Code")
                        .IsUnique();

                    b.ToTable("account_promos", (string)null);
                });

            modelBuilder.Entity("BAR.Database.Entities.Balance", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_id");

                    b.Property<long>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(100L)
                        .HasColumnName("balance");

                    b.HasKey("AccountId");

                    b.ToTable("balances", (string)null);
                });

            modelBuilder.Entity("BAR.Database.Entities.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BasePrice")
                        .HasColumnType("integer")
                        .HasColumnName("base_price");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_hidden");

                    b.Property<bool>("IsNight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_night");

                    b.Property<int>("MinDrinkCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("min_drink_count");

                    b.Property<int>("MoodPriceModifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mood_price_modifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("drinks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 15,
                            IsHidden = false,
                            IsNight = false,
                            MinDrinkCount = 0,
                            MoodPriceModifier = 0,
                            Name = "Куба Либре"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 12,
                            IsHidden = false,
                            IsNight = false,
                            MinDrinkCount = 0,
                            MoodPriceModifier = 0,
                            Name = "Отвёртка"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 14,
                            IsHidden = false,
                            IsNight = false,
                            MinDrinkCount = 0,
                            MoodPriceModifier = 0,
                            Name = "Джин-тоник"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 13,
                            IsHidden = false,
                            IsNight = false,
                            MinDrinkCount = 0,
                            MoodPriceModifier = 0,
                            Name = "Виски-кола"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 14,
                            IsHidden = false,
                            IsNight = false,
                            MinDrinkCount = 0,
                            MoodPriceModifier = 0,
                            Name = "Текила-санрайз"
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 10,
                            IsHidden = false,
                            IsNight = false,
                            MinDrinkCount = 0,
                            MoodPriceModifier = 0,
                            Name = "Русский"
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 16,
                            IsHidden = false,
                            IsNight = false,
                            MinDrinkCount = 0,
                            MoodPriceModifier = 0,
                            Name = "Белый русский"
                        },
                        new
                        {
                            Id = 8,
                            BasePrice = 25,
                            IsHidden = false,
                            IsNight = false,
                            MinDrinkCount = 0,
                            MoodPriceModifier = 0,
                            Name = "Лонг-Айленд"
                        },
                        new
                        {
                            Id = 9,
                            BasePrice = 8,
                            IsHidden = false,
                            IsNight = true,
                            MinDrinkCount = 0,
                            MoodPriceModifier = 0,
                            Name = "Ночной русский"
                        },
                        new
                        {
                            Id = 10,
                            BasePrice = 10,
                            IsHidden = false,
                            IsNight = true,
                            MinDrinkCount = 0,
                            MoodPriceModifier = 0,
                            Name = "Бессонница"
                        },
                        new
                        {
                            Id = 11,
                            BasePrice = 12,
                            IsHidden = false,
                            IsNight = true,
                            MinDrinkCount = 0,
                            MoodPriceModifier = 0,
                            Name = "Лунный свет"
                        },
                        new
                        {
                            Id = 12,
                            BasePrice = 0,
                            IsHidden = true,
                            IsNight = false,
                            MinDrinkCount = 0,
                            MoodPriceModifier = 0,
                            Name = "Мертвец"
                        });
                });

            modelBuilder.Entity("BAR.Database.Entities.DrinkIngredient", b =>
                {
                    b.Property<int>("DrinkId")
                        .HasColumnType("integer")
                        .HasColumnName("drink_id");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.HasKey("DrinkId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("drink_ingredients", (string)null);

                    b.HasData(
                        new
                        {
                            DrinkId = 1,
                            IngredientId = 2
                        },
                        new
                        {
                            DrinkId = 1,
                            IngredientId = 6
                        },
                        new
                        {
                            DrinkId = 1,
                            IngredientId = 9
                        },
                        new
                        {
                            DrinkId = 2,
                            IngredientId = 1
                        },
                        new
                        {
                            DrinkId = 2,
                            IngredientId = 7
                        },
                        new
                        {
                            DrinkId = 3,
                            IngredientId = 5
                        },
                        new
                        {
                            DrinkId = 3,
                            IngredientId = 8
                        },
                        new
                        {
                            DrinkId = 3,
                            IngredientId = 9
                        },
                        new
                        {
                            DrinkId = 4,
                            IngredientId = 4
                        },
                        new
                        {
                            DrinkId = 4,
                            IngredientId = 6
                        },
                        new
                        {
                            DrinkId = 5,
                            IngredientId = 3
                        },
                        new
                        {
                            DrinkId = 5,
                            IngredientId = 7
                        },
                        new
                        {
                            DrinkId = 6,
                            IngredientId = 1
                        },
                        new
                        {
                            DrinkId = 6,
                            IngredientId = 9
                        },
                        new
                        {
                            DrinkId = 7,
                            IngredientId = 1
                        },
                        new
                        {
                            DrinkId = 7,
                            IngredientId = 9
                        },
                        new
                        {
                            DrinkId = 7,
                            IngredientId = 10
                        },
                        new
                        {
                            DrinkId = 8,
                            IngredientId = 1
                        },
                        new
                        {
                            DrinkId = 8,
                            IngredientId = 2
                        },
                        new
                        {
                            DrinkId = 8,
                            IngredientId = 3
                        },
                        new
                        {
                            DrinkId = 8,
                            IngredientId = 5
                        },
                        new
                        {
                            DrinkId = 8,
                            IngredientId = 6
                        },
                        new
                        {
                            DrinkId = 9,
                            IngredientId = 1
                        },
                        new
                        {
                            DrinkId = 9,
                            IngredientId = 9
                        },
                        new
                        {
                            DrinkId = 9,
                            IngredientId = 10
                        },
                        new
                        {
                            DrinkId = 10,
                            IngredientId = 2
                        },
                        new
                        {
                            DrinkId = 10,
                            IngredientId = 6
                        },
                        new
                        {
                            DrinkId = 10,
                            IngredientId = 8
                        },
                        new
                        {
                            DrinkId = 11,
                            IngredientId = 5
                        },
                        new
                        {
                            DrinkId = 11,
                            IngredientId = 7
                        },
                        new
                        {
                            DrinkId = 11,
                            IngredientId = 8
                        },
                        new
                        {
                            DrinkId = 12,
                            IngredientId = 1
                        },
                        new
                        {
                            DrinkId = 12,
                            IngredientId = 2
                        },
                        new
                        {
                            DrinkId = 12,
                            IngredientId = 10
                        });
                });

            modelBuilder.Entity("BAR.Database.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ingredients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "водка"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ром"
                        },
                        new
                        {
                            Id = 3,
                            Name = "текила"
                        },
                        new
                        {
                            Id = 4,
                            Name = "виски"
                        },
                        new
                        {
                            Id = 5,
                            Name = "джин"
                        },
                        new
                        {
                            Id = 6,
                            Name = "кола"
                        },
                        new
                        {
                            Id = 7,
                            Name = "сок"
                        },
                        new
                        {
                            Id = 8,
                            Name = "тоник"
                        },
                        new
                        {
                            Id = 9,
                            Name = "лёд"
                        },
                        new
                        {
                            Id = 10,
                            Name = "молоко"
                        });
                });

            modelBuilder.Entity("BAR.Database.Entities.MoodTracking", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_id");

                    b.Property<int>("ConsecutiveSimilarOrders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("consecutive_similar_orders");

                    b.Property<string>("LastDrink")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_drink");

                    b.Property<DateTime?>("LastOrderTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_order_time");

                    b.Property<string>("MoodLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("normal")
                        .HasColumnName("mood_level");

                    b.HasKey("AccountId");

                    b.ToTable("mood_tracking", (string)null);
                });

            modelBuilder.Entity("BAR.Database.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Drink")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("drink");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("method");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("BAR.Database.Entities.OrderSequence", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_id");

                    b.Property<string>("DrinkName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("drink_name");

                    b.Property<int>("SequenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sequence_count");

                    b.HasKey("AccountId", "DrinkName");

                    b.ToTable("order_sequence", (string)null);
                });

            modelBuilder.Entity("BAR.Database.Entities.Profile", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_id");

                    b.Property<bool>("BarClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bar_closed");

                    b.Property<string>("FavoriteDrink")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("favorite_drink");

                    b.Property<bool>("HasFreeDrink")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_free_drink");

                    b.Property<bool>("HasNightAccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_night_access");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Новичок")
                        .HasColumnName("rank");

                    b.Property<int>("TotalOrders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_orders");

                    b.Property<int>("UniqueDrinks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("unique_drinks");

                    b.HasKey("AccountId");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("BAR.Database.Entities.PromoCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BonusBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("bonus_balance");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("FreeDrink")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("free_drink");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<string>("MoodEffect")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mood_effect");

                    b.Property<bool>("NightAccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("night_access");

                    b.Property<int>("UsesLeft")
                        .HasColumnType("integer")
                        .HasColumnName("uses_left");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("promo_codes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BonusBalance = 0,
                            Code = "ANTIHACK",
                            FreeDrink = false,
                            IsEnabled = true,
                            MaxUses = 3,
                            NightAccess = false,
                            UsesLeft = 3
                        },
                        new
                        {
                            Id = 2,
                            BonusBalance = 0,
                            Code = "FREESHOT",
                            FreeDrink = true,
                            IsEnabled = true,
                            MaxUses = 1,
                            NightAccess = false,
                            UsesLeft = 1
                        },
                        new
                        {
                            Id = 3,
                            BonusBalance = 50,
                            Code = "RICHBOY",
                            FreeDrink = false,
                            IsEnabled = true,
                            NightAccess = false,
                            UsesLeft = 999999
                        },
                        new
                        {
                            Id = 4,
                            BonusBalance = 50,
                            Code = "GOODMOOD",
                            FreeDrink = false,
                            IsEnabled = true,
                            MoodEffect = "generous",
                            NightAccess = false,
                            UsesLeft = 999999
                        },
                        new
                        {
                            Id = 5,
                            BonusBalance = 0,
                            Code = "NIGHT",
                            FreeDrink = false,
                            IsEnabled = true,
                            NightAccess = true,
                            UsesLeft = 999999
                        },
                        new
                        {
                            Id = 6,
                            BonusBalance = 0,
                            Code = "LEGEND",
                            FreeDrink = false,
                            IsEnabled = true,
                            MaxUses = 5,
                            NightAccess = false,
                            UsesLeft = 5
                        });
                });

            modelBuilder.Entity("BAR.Database.Entities.PromoSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("PromoEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("promo_enabled");

                    b.HasKey("Id");

                    b.ToTable("promo_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PromoEnabled = true
                        });
                });

            modelBuilder.Entity("BAR.Database.Entities.RateLimit", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_id");

                    b.Property<int>("RequestCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("request_count");

                    b.Property<DateTime>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.HasKey("AccountId");

                    b.ToTable("rate_limits", (string)null);
                });

            modelBuilder.Entity("BAR.Database.Entities.AccountPromo", b =>
                {
                    b.HasOne("BAR.Database.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BAR.Database.Entities.Balance", b =>
                {
                    b.HasOne("BAR.Database.Entities.Account", "Account")
                        .WithOne("Balance")
                        .HasForeignKey("BAR.Database.Entities.Balance", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BAR.Database.Entities.DrinkIngredient", b =>
                {
                    b.HasOne("BAR.Database.Entities.Drink", "Drink")
                        .WithMany("DrinkIngredients")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BAR.Database.Entities.Ingredient", "Ingredient")
                        .WithMany("DrinkIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("BAR.Database.Entities.MoodTracking", b =>
                {
                    b.HasOne("BAR.Database.Entities.Account", "Account")
                        .WithOne("MoodTracking")
                        .HasForeignKey("BAR.Database.Entities.MoodTracking", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BAR.Database.Entities.Order", b =>
                {
                    b.HasOne("BAR.Database.Entities.Account", "Account")
                        .WithMany("Orders")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BAR.Database.Entities.OrderSequence", b =>
                {
                    b.HasOne("BAR.Database.Entities.Account", "Account")
                        .WithMany("OrderSequences")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BAR.Database.Entities.Profile", b =>
                {
                    b.HasOne("BAR.Database.Entities.Account", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("BAR.Database.Entities.Profile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BAR.Database.Entities.RateLimit", b =>
                {
                    b.HasOne("BAR.Database.Entities.Account", "Account")
                        .WithOne("RateLimit")
                        .HasForeignKey("BAR.Database.Entities.RateLimit", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BAR.Database.Entities.Account", b =>
                {
                    b.Navigation("Balance");

                    b.Navigation("MoodTracking");

                    b.Navigation("OrderSequences");

                    b.Navigation("Orders");

                    b.Navigation("Profile");

                    b.Navigation("RateLimit");
                });

            modelBuilder.Entity("BAR.Database.Entities.Drink", b =>
                {
                    b.Navigation("DrinkIngredients");
                });

            modelBuilder.Entity("BAR.Database.Entities.Ingredient", b =>
                {
                    b.Navigation("DrinkIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
